const WINNING_CASES = [
    // Horizontales
    ['ACB', 'BCA', 'CCB'],
    ['ACB', 'BCB', 'CCB'],
    ['ACB', 'BCC', 'CCB'],
    ['ABA', 'BAA', 'CBA'],
    ['ABA', 'BBA', 'CBA'],
    ['ABA', 'BCA', 'CBA'],
    ['ABC', 'BAC', 'CBC'],
    ['ABC', 'BBC', 'CBC'],
    ['ABC', 'BCC', 'CBC'],
    ['AAB', 'BAA', 'CAB'],
    ['AAB', 'BAB', 'CAB'],
    ['AAB', 'BAC', 'CAB'],
    // Verticales
    ['ACB', 'ABA', 'AAB'],
    ['ACB', 'ABB', 'AAB'],
    ['ACB', 'ABC', 'AAB'],
    ['BCA', 'ABA', 'BAA'],
    ['BCA', 'BBA', 'BAA'],
    ['BCA', 'CBA', 'BAA'],
    ['BCC', 'ABC', 'BAC'],
    ['BCC', 'BBC', 'BAC'],
    ['BCC', 'CBC', 'BAC'],
    ['CCB', 'CBA', 'CAB'],
    ['CCB', 'CBB', 'CAB'],
    ['CCB', 'CBC', 'CAB'],
    // Sagitales
    ['BCA', 'ACB', 'BCC'],
    ['BCA', 'BCB', 'BCC'],
    ['BCA', 'CCB', 'BCC'],
    ['ABA', 'AAB', 'ABC'],
    ['ABA', 'ABB', 'ABC'],
    ['ABA', 'ACB', 'ABC'],
    ['BAA', 'AAB', 'BAC'],
    ['BAA', 'BAB', 'BAC'],
    ['BAA', 'CAB', 'BAC'],
    ['CBA', 'CAB', 'CBC'],
    ['CBA', 'CBB', 'CBC'],
    ['CBA', 'CCB', 'CBC'],
    // Diagonales
    ['ABA', 'BCB', 'CBC'],
    ['ABA', 'BAB', 'CBC'],
    ['ACB', 'BBA', 'CAB'],
    ['ACB', 'BBC', 'CAB'],
    ['BCA', 'ABB', 'BAC'],
    ['BCA', 'CBB', 'BAC'],
    ['BCC', 'ABB', 'BAA'],
    ['BCC', 'CBB', 'BAA'],
    ['CBA', 'BAB', 'ABC'],
    ['CBA', 'BCB', 'ABC'],
    ['CCB', 'BBA', 'AAB'],
    ['CCB', 'BBC', 'AAB']
]

export default WINNING_CASES;